version: '3'

services:
  django_app:
    build: .
    command: gunicorn stock.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./dalal/.env
    environment:
      # - HTTP_PROXY=http://django_app:8000
      # - HTTPS_PROXY=https://django_app:8000
      - NO_PROXY=localhost,127.0.0.1
    volumes:
      - static_vol:/ds/dalal/static
      - media_vol:/ds/dalal/static/media
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    environment:
      # - HTTP_PROXY=http://django_app:8000
      # - HTTPS_PROXY=https://django_app:8000
      - NO_PROXY=localhost,127.0.0.1
    volumes:
      - static_vol:/ds/dalal/static
      - media_vol:/ds/dalal/static/media
    ports:
      - "80:80"
    depends_on:
      - django_app
volumes:
  static_vol:
  media_vol:
